Create simple documentation for @typeofweb/schema library
typeofweb/schema pull request #1
Opened 2021-01-12 21:38 UTC by wisnie

2021-01-12 21:46 UTC, mmiszy requested changes

2021-01-12 21:46 UTC, mmiszy commented on README.md
> +const numberSchema = string();
```suggestion
const numberSchema = number();
```

2021-01-12 21:46 UTC, mmiszy commented on README.md
> +const booleanSchema = string();
```suggestion
const booleanSchema = boolean();
```

2021-01-12 21:46 UTC, mmiszy commented on README.md
> +Generates schema that will match all values specifiec in the schemas in the array.
```suggestion
Generates schema that will match all values specified in the schemas in the array.
```

2021-01-12 21:46 UTC, mmiszy commented on README.md
> +```
It would be nice to mention that null/undefined also pass the validation

2021-01-12 21:58 UTC, AdamSiekierski requested changes

2021-01-12 21:58 UTC, AdamSiekierski commented on README.md
> +Generates schema that will match number.
```suggestion
Generates schema that will match a number.
```

2021-01-12 21:58 UTC, AdamSiekierski commented on README.md
> +Generates schema that will match string.
```suggestion
Generates schema that will match a string.
```

2021-01-12 21:58 UTC, AdamSiekierski commented on README.md
> +Generates a schema which will match only specified values.
```suggestion
Generates a schema which will match only the specified values.
```

2021-01-12 21:58 UTC, AdamSiekierski commented on README.md
> +Generates schema that will match boolean.
```suggestion
Generates schema that will match a boolean.
```

2021-01-12 21:58 UTC, AdamSiekierski commented on README.md
> +Generates schema that will match date.
```suggestion
Generates schema that will match a JavaScript Date object.
```

2021-01-12 21:58 UTC, AdamSiekierski commented on README.md
> +Generates schema that will match object.
```suggestion
Generates schema that will match a object.
```

2021-01-12 21:58 UTC, AdamSiekierski commented on README.md
> +Generates schema that will match all values specified in the schemas in the array.
```suggestion
Generates a schema that will match all the values specified by the schemas passed in the array.
```

2021-01-13 00:35 UTC, mmiszy requested changes

2021-01-13 00:35 UTC, mmiszy commented on README.md
> +@typeofweb/schema is lightweight, extensible library for data validation.
```suggestion
@typeofweb/schema is a lightweight and extensible library for data validation with full support for TypeScript!
```

2021-01-13 00:35 UTC, mmiszy commented on README.md
> +Install package with npm:
```suggestion
Install the package with npm:
```

2021-01-13 00:35 UTC, mmiszy commented on README.md
> +Install package with yarn:
```suggestion
or install the package with yarn:
```

2021-01-13 00:35 UTC, mmiszy commented on README.md
> +Generates a schema which will match only specified values.
To chyba nie jest poprawnie? :P

2021-01-13 00:35 UTC, mmiszy commented on README.md
> +Generates a schema which will match only specified values.
```suggestion
Generates a schema which matches only specified values.
```

2021-01-13 00:35 UTC, mmiszy commented on README.md
> +// Throws validation error
```suggestion
// Throws ValidationError
```

2021-01-13 00:35 UTC, mmiszy commented on README.md
> +Generates schema that will match string.
```suggestion
Creates a schema that matches strings.
```

2021-01-13 00:35 UTC, mmiszy commented on README.md
> +Generates schema that will match number.
```suggestion
Creates a schema that matches numbers.
```

2021-01-13 00:35 UTC, mmiszy commented on README.md
> +// Return 3.14
```suggestion
// Returns 3.14
```

2021-01-13 00:35 UTC, mmiszy commented on README.md
> +Generates schema that will match boolean.
```suggestion
Creates a schema that matches booleans.
```

2021-01-13 00:35 UTC, mmiszy commented on README.md
> +Generates schema that will match date.
```suggestion
Creates a schema that matches JavaScript `Date` objects.
```

2021-01-13 00:35 UTC, mmiszy commented on README.md
> +Generates schema that will match object.
```suggestion
Creates a schema that matches objects of provided shape.
```

2021-01-13 00:35 UTC, mmiszy commented on README.md
> +```js
```suggestion
```ts
```

2021-01-13 00:35 UTC, mmiszy commented on README.md
> +  manufacturer: 'Typeofweb enterprise',
```suggestion
  manufacturer: 'Type of Web Enterprise',
```

2021-01-13 00:35 UTC, mmiszy commented on README.md
> +Generates schema that will match all values specified in the schemas in the array.
```suggestion
Creates a schema that matches arrays containing values specified by the schemas passed in the array.
```

2021-01-13 00:35 UTC, mmiszy commented on README.md
> +```
We could use an example with more than one schema inside the array

2021-01-13 00:35 UTC, mmiszy commented on README.md
> +Modifers are used to customize the schema and change the validation behaviour.
```suggestion
Modifiers are used to customize schemas and change their validation behaviour.
```

2021-01-13 00:35 UTC, mmiszy commented on README.md
> +If you use nullable modifier, output type will be `null | InferredType`.
```suggestion
If you use the `nullable` modifier, given schema will be extended to also match `null` values, and its output type will be `null | T`.
```

2021-01-13 00:35 UTC, mmiszy commented on README.md
> +// Throws validation error
```suggestion
// Throws ValidationError
```

2021-01-13 00:35 UTC, mmiszy commented on README.md
> +If you use optional modifier, output type will be `undefined | InferredType`.
```suggestion
If you use the `optional` modifier, given schema will be extended to also match `undefined` values, and its output type will be `undefined | T`.
```

2021-01-13 00:35 UTC, mmiszy commented on README.md
> +If you use nil modifier, output type will be `undefined | null | InferredType`.
```suggestion
If you use the `nil` modifier, given schema will be extended to also match `null` and `undefined` values, and its output type will be `null | undefined | T`.
```

2021-01-13 00:39 UTC, mmiszy requested changes

2021-01-13 00:39 UTC, mmiszy commented on README.md
> +```js
```suggestion
```ts
```

2021-01-13 00:39 UTC, mmiszy commented on README.md
> +```js
```suggestion
```ts
```

2021-01-13 00:39 UTC, mmiszy commented on README.md
> +```js
```suggestion
```ts
```

2021-01-13 00:39 UTC, mmiszy commented on README.md
> +```js
```suggestion
```ts
```

2021-01-13 00:39 UTC, mmiszy commented on README.md
> +```js
```suggestion
```ts
```

2021-01-13 00:39 UTC, mmiszy commented on README.md
> +```js
```suggestion
```ts
```

2021-01-13 00:39 UTC, mmiszy commented on README.md
> +```js
```suggestion
```ts
```

2021-01-13 00:39 UTC, mmiszy commented on README.md
> +```js
```suggestion
```ts
```

2021-01-13 00:39 UTC, mmiszy commented on README.md
> +```js
```suggestion
```ts
```

2021-01-13 00:41 UTC, mmiszy approved these changes

2021-01-13 00:42 UTC, merged